name: Friend Link request
description: Creating friend link
title: '[Friend Link Request]'
labels:
  - 'Friend Request'
assignees:
  - Esonhugh # 这里改成你的GitHub ID
body:
  - type: input
    id: alias
    attributes:
      label: your name
      placeholder: your name
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: site url
      placeholder: https://example.com/avatar.png
    validations:
      required: true
  - type: input
    id: remark
    attributes:
      label: site description
      placeholder: site description
    validations:
      required: true
  - type: input
    id: avator
    attributes:
      label: your logo
      description: your logo or site favicon
      placeholder: https://example.com/avatar.png
    validations:
      required: true
  - type: textarea
    id: message
    attributes:
      label: more detail.
